version: '2'
services:
  vinylmgt-app:
    image: vinylmgt
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://vinylmgt-postgresql:5432/vinylmgt
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=azerty
    ports:
      - "8080:8080"
  vinylmgt-postgresql:
    extends:
      file: postgresql.yml
      service: vinylmgt-postgresql
